const singer = [
    {
        name: 'Atif Aslam',
        country: 'Pakisthan',
        age: 34,
        gender: 'Male',
        img: 'https://www.celebritycontactdetails.com/wp-content/uploads/2020/08/Singer-Atif-Aslam-Contact.jpg',
        populiti: '35M',
        cost: '16,00,000',
        location: 'Mombai',
        role: 'Singer',
        religion: 'Islam'
    },
    {
        name: 'Arjit Singh',
        country: 'India',
        age: 37,
        gender: 'Male',
        img: 'https://www.jagranimages.com/images/newimg/20052021/20_05_2021-arijit_singh_21660518.jpg',
        populiti: '45M',
        cost: '18,00,000',
        location: 'Mombai',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Tulsi Kumar',
        country: 'India',
        age: 28,
        gender: 'Female',
        img: 'https://c.ndtvimg.com/2021-05/rh2mmvr8_tulsi-kumar_625x300_03_May_21.jpg',
        populiti: '45M',
        cost: '14,00,000',
        location: 'Mombai',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Badshah',
        country: 'India',
        age: 35,
        gender: 'Male',
        img: 'https://english.cdn.zeenews.com/sites/default/files/2020/08/06/877373-badshah.jpg',
        populiti: '45M',
        cost: '17,00,000',
        location: 'Delhi',
        role: 'Rab Singer',
        religion: 'Hindu'
    },
    {
        name: 'Yo Yo Honey Singh',
        country: 'India',
        age: 41,
        gender: 'Male',
        img: 'https://www.bollywoodhungama.com/wp-content/uploads/2021/08/WhatsApp-Image-2021-08-03-at-6.24.29-PM.jpeg',
        populiti: '45M',
        cost: '16,00,000',
        location: 'Mombai',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'B Praak',
        country: 'India',
        age: 38,
        gender: 'Male',
        img: 'https://popmellow.com/wp-content/uploads/2021/06/Top-20-Most-Popular-Bollywood-Singers.jpg',
        populiti: '45M',
        cost: '15,00,000',
        location: 'Panjab',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Jubin Nautiyal',
        country: 'India',
        age: 34,
        gender: 'Male',
        img: 'https://static.toiimg.com/photo/msid-74993593/74993593.jpg?195468',
        populiti: '45M',
        cost: '14,00,000',
        location: 'Bandalu',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Guru Randhawa',
        country: 'India',
        age: 36,
        gender: 'Male',
        img: 'https://static.toiimg.com/photo/msid-82254048/82254048.jpg?195186',
        populiti: '45M',
        cost: '17,00,000',
        location: 'Gujrat',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Darshan Raval',
        country: 'India',
        age: 33,
        gender: 'Male',
        img: 'https://i.scdn.co/image/ab6761610000e5eb61e352af80cf3746c61e10a4',
        populiti: '45M',
        cost: '12,00,000',
        location: 'Kolikata',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Neha Kakkar',
        country: 'India',
        age: 31,
        gender: 'Female',
        img: 'https://bollyhollybaba.com/wp-content/uploads/2019/12/Neha-kakkar-biographysingerCareer.jpg',
        populiti: '45M',
        cost: '16,00,000',
        location: 'Haiderbad',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Dhvani Bhanushali',
        country: 'India',
        age: 27,
        gender: 'Female',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThAyvs3AbjIfnlFM2J-OavZtkES8VBTAAG63ZHyi2I4AlSNidMX2J-_dhf2V4tOmHA0Pw&usqp=CAU',
        populiti: '45M',
        cost: '13,00,000',
        location: 'Mombai',
        role: 'Singer',
        religion: 'Hindu'
    },
    {
        name: 'Tony Kakkar',
        country: 'India',
        age: 28,
        gender: 'Male',
        img: 'https://filmyvoice.com/wp-content/uploads/2021/07/Tony-Kakkar.jpg',
        populiti: '45M',
        cost: '9,00,000',
        location: 'Gujrat',
        role: 'Singer',
        religion: 'Hindu'
    }
]